from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
SHARED = ROOT / "tmp/pdfs/next-three/build_next_three_packs.py"
namespace = {}
exec(SHARED.read_text().split("# P1 DAY 4")[0], namespace)
globals().update(namespace)

OUT = ROOT / "output/pdf/next-10-days"


def math_pack(spec):
    story = []
    story += cover(spec["kicker"], spec["title"], spec["subtitle"], spec["aim"],
                   "Read the notes and copy each worked step. Attempt every question before opening page 4. Mark in another colour and repair every error.")
    story += page_title("Learn from zero", "The ideas you need", spec["intro"])
    for note in spec["notes"]:
        story.append(bullet(note))
    story += [Spacer(1, 5), callout("Memory rule", spec["memory"], BLUE_LIGHT, BLUE), Spacer(1, 7)]
    for heading, body in spec["worked"]:
        story += [P(heading, "H2x"), callout("Worked steps", body, TEAL_LIGHT, TEAL), Spacer(1, 5)]
    story += [PageBreak()]
    story += page_title("Your turn", "Independent practice", "Show every step. Include units in Mechanics.")
    rows = [["Question", "Working and final answer"]] + [[q, ""] for q in spec["questions"]]
    story += [table(rows, [84*mm, 90*mm], heights=[9*mm] + [29*mm]*len(spec["questions"])),
              Spacer(1, 7), callout("Stop", "Do not continue until all six questions have an attempt.", ORANGE_LIGHT, ORANGE), PageBreak()]
    story += page_title("Answer section", "Mark, diagnose, correct", "A wrong answer is useful only when you repair the first wrong step.")
    story += [table([["Q", "Answer and essential working"]] + [[str(i+1), a] for i, a in enumerate(spec["answers"])],
                    [16*mm, 158*mm]), Spacer(1, 8),
              table([["Q", "First wrong step", "Correct rule"]] + [["", "", ""] for _ in range(3)],
                    [18*mm, 77*mm, 79*mm], heights=[9*mm]+[20*mm]*3), Spacer(1, 7),
              callout("Send for marking", "Send pages 3 and 4. Ask for a score, the first error in each answer, and one follow-up question per weak skill.", GREEN_LIGHT, TEAL)]
    path = OUT / spec["filename"]
    build(str(path), spec["title"], spec["subtitle"], spec["footer"], story)
    return path


def business_pack(spec):
    story = []
    story += cover(spec["kicker"], spec["title"], spec["subtitle"], spec["aim"],
                   "Read the notes twice. Use exact case facts. Every explanation must contain a because link and a therefore business impact. Keep page 4 closed.")
    story += page_title("Learn from zero", "Knowledge and method", spec["intro"])
    for note in spec["notes"]:
        story.append(bullet(note))
    story += [Spacer(1, 6), callout("Mini case", spec["case"], CREAM, INK), Spacer(1, 6),
              callout("Worked chain", spec["worked"], TEAL_LIGHT, TEAL), PageBreak()]
    story += page_title("Your turn", "Knowledge, application and analysis", "Use the mini case in Questions 3-6.")
    rows = [["Question", "Your answer"]] + [[q, ""] for q in spec["questions"]]
    story += [table(rows, [91*mm, 83*mm], heights=[9*mm]+[29*mm]*len(spec["questions"])), Spacer(1, 7),
              callout("Quality check", "Circle every case fact. Underline every because link. Box every business impact.", ORANGE_LIGHT, ORANGE), PageBreak()]
    story += page_title("Answer section", "Models and correction log", "Wording may differ, but the knowledge and chains must be accurate.")
    story += [table([["Q", "Answer / model points"]] + [[str(i+1), a] for i, a in enumerate(spec["answers"])],
                    [16*mm, 158*mm]), Spacer(1, 7),
              table([["Q", "Missing layer", "My improved sentence"]] + [["", "", ""] for _ in range(3)],
                    [18*mm, 61*mm, 95*mm], heights=[9*mm]+[20*mm]*3), Spacer(1, 7),
              callout("Send for marking", "Send pages 3 and 4. Ask for a level, missing chains, and a rewritten model for the weakest response.", GREEN_LIGHT, TEAL)]
    path = OUT / spec["filename"]
    build(str(path), spec["title"], spec["subtitle"], spec["footer"], story)
    return path


P1 = [
dict(day=5, filename="p1-day-05-coordinate-geometry.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 5", title="Coordinate geometry", subtitle="Gradients, distances, midpoints and straight lines", aim="Build straight-line geometry from the coordinate basics.", intro="A point is written (x, y). A line is controlled by its gradient and one point.", notes=["Gradient m=(change in y)/(change in x).", "Midpoint of (x1,y1) and (x2,y2) is ((x1+x2)/2,(y1+y2)/2).", "Distance is sqrt((x2-x1)^2+(y2-y1)^2).", "Line through (x1,y1): y-y1=m(x-x1).", "Parallel lines have equal gradients; perpendicular gradients multiply to -1."], memory="Find the gradient first, then substitute one known point.", worked=[("Line through two points","Through (2,3) and (6,11): m=(11-3)/(6-2)=2. So y-3=2(x-2), hence y=2x-1."),("Perpendicular line","A line perpendicular to y=3x+4 has gradient -1/3.")], questions=["1. Find the gradient from (1,2) to (5,10).","2. Find the midpoint of (-2,5) and (6,-1).","3. Find the distance between (1,1) and (4,5).","4. Find the equation through (3,2) with gradient 4.","5. Find the equation through (1,5) and (3,1).","6. Find the perpendicular bisector of (0,0) and (4,2)."], answers=["m=(10-2)/(5-1)=2.","(2,2).","sqrt(3^2+4^2)=5.","y-2=4(x-3), so y=4x-10.","m=-2; y-5=-2(x-1), so y=-2x+7.","Midpoint (2,1); segment gradient 1/2, so perpendicular gradient -2. y-1=-2(x-2), so y=-2x+5."], footer="Rohan Study System | P1 Day 5"),
dict(day=6, filename="p1-day-06-circles.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 6", title="Circles", subtitle="Centre, radius, equations and tangents", aim="Read and build circle equations, then use radius-tangent geometry.", intro="A circle is every point the same distance from its centre.", notes=["Centre (a,b), radius r: (x-a)^2+(y-b)^2=r^2.", "The signs reverse inside brackets: (x+3)^2 gives centre x=-3.", "Expand only when asked; completed-square form shows the geometry.", "A tangent is perpendicular to the radius at the point of contact."], memory="Centre signs reverse; tangent gradient is the negative reciprocal of radius gradient.", worked=[("Read a circle","(x-2)^2+(y+1)^2=25 has centre (2,-1) and radius 5."),("Tangent","Centre (0,0), point (3,4): radius gradient 4/3, tangent gradient -3/4; y-4=(-3/4)(x-3).")], questions=["1. State centre and radius of (x+1)^2+(y-4)^2=9.","2. Write the circle with centre (3,-2), radius 4.","3. Does (4,3) lie on x^2+y^2=25?","4. Complete squares: x^2+y^2-6x+4y-12=0.","5. Find the tangent to x^2+y^2=25 at (3,4).","6. Find intersections of x^2+y^2=25 with y=4."], answers=["Centre (-1,4), radius 3.","(x-3)^2+(y+2)^2=16.","Yes: 16+9=25.","(x-3)^2+(y+2)^2=25.","y-4=(-3/4)(x-3), or 3x+4y=25.","x^2+16=25, so x=3 or -3: (3,4), (-3,4)."], footer="Rohan Study System | P1 Day 6"),
dict(day=7, filename="p1-day-07-radians.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 7", title="Radians", subtitle="Angles, arcs, sectors and segments", aim="Use radians confidently in exact geometry problems.", intro="Radians measure an angle using arc length divided by radius.", notes=["pi radians=180 degrees.", "Degrees to radians: multiply by pi/180.", "Arc length s=r theta.", "Sector area=(1/2)r^2 theta.", "Segment area=sector area-triangle area=(1/2)r^2(theta-sin theta)."], memory="The arc and sector formulas require theta in radians.", worked=[("Convert","60 degrees=60(pi/180)=pi/3."),("Sector","r=6, theta=1.2: arc=7.2; area=0.5(36)(1.2)=21.6.")], questions=["1. Convert 135 degrees to radians.","2. Convert 5pi/6 radians to degrees.","3. Find arc length when r=8, theta=0.75.","4. Find sector area when r=5, theta=1.4.","5. Find the perimeter of that sector.","6. Find segment area for r=4, theta=pi/3."], answers=["3pi/4.","150 degrees.","s=8(0.75)=6.","0.5(25)(1.4)=17.5.","2r+s=10+7=17.","0.5(16)(pi/3-sin(pi/3))=8pi/3-4sqrt(3)."], footer="Rohan Study System | P1 Day 7"),
dict(day=8, filename="p1-day-08-trigonometry.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 8", title="Trigonometry", subtitle="Identities and equations", aim="Simplify expressions and solve trigonometric equations over an interval.", intro="An identity is true for every allowed angle; an equation is true only for selected angles.", notes=["sin^2 x+cos^2 x=1.", "tan x=sin x/cos x.", "For sin x=k, use the sine symmetry; for cos x=k, use cosine symmetry.", "For tan x=k, solutions repeat every 180 degrees.", "Always check the stated interval."], memory="Find the reference angle, choose the correct quadrants, then check the interval.", worked=[("Identity","(1-cos^2 x)/sin x=sin^2 x/sin x=sin x."),("Equation","2sin x=1 on 0 to 360: sin x=1/2, so x=30,150 degrees.")], questions=["1. Simplify sin x/cos x.","2. Simplify 1-sin^2 x.","3. Solve sin x=sqrt(3)/2 for 0<=x<=360 degrees.","4. Solve cos x=-1/2 on the same interval.","5. Solve tan x=1 on the same interval.","6. Solve 2cos^2 x-1=0 on the same interval."], answers=["tan x.","cos^2 x.","60, 120 degrees.","120, 240 degrees.","45, 225 degrees.","cos^2 x=1/2, so x=45,135,225,315 degrees."], footer="Rohan Study System | P1 Day 8"),
dict(day=9, filename="p1-day-09-binomial.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 9", title="Binomial expansion", subtitle="Coefficients and selected terms", aim="Expand positive integer powers and locate a required coefficient.", intro="The coefficients in (a+b)^n come from combinations.", notes=["General term: C(n,r)a^(n-r)b^r.", "r starts at 0, so the (r+1)th term uses r.", "Signs alternate for (a-b)^n.", "For a selected coefficient, track both number and power of x."], memory="Write C(n,r), then the first term power falls while the second rises.", worked=[("Expansion","(1+2x)^3=1+3(2x)+3(2x)^2+(2x)^3=1+6x+12x^2+8x^3."),("Selected term","x^2 in (2+x)^5 uses r=2: C(5,2)2^3x^2=80x^2.")], questions=["1. Expand (1+x)^4.","2. Expand (2-x)^3.","3. Find coefficient of x^2 in (1+3x)^5.","4. Find coefficient of x^3 in (2+x)^6.","5. Find first four terms of (1-2x)^5.","6. Find constant term in (x+2/x)^4."], answers=["1+4x+6x^2+4x^3+x^4.","8-12x+6x^2-x^3.","C(5,2)3^2=90.","C(6,3)2^3=160.","1-10x+40x^2-80x^3.","Power x^(4-r)x^(-r)=x^(4-2r); constant when r=2. C(4,2)2^2=24."], footer="Rohan Study System | P1 Day 9"),
dict(day=10, filename="p1-day-10-series.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 10", title="Sequences and series", subtitle="Arithmetic and geometric progressions", aim="Find terms and sums, then decide which model applies.", intro="A progression follows a fixed rule from one term to the next.", notes=["AP: common difference d; nth term a+(n-1)d.", "AP sum: n/2[2a+(n-1)d].", "GP: common ratio r; nth term ar^(n-1).", "GP sum: a(1-r^n)/(1-r).", "Infinite GP sum a/(1-r) only when |r|<1."], memory="Subtract neighbouring terms for an AP; divide them for a GP.", worked=[("AP","3,7,11,... has a=3,d=4. Term 20=3+19(4)=79."),("GP","5,10,20,... has a=5,r=2. Sum first 4=5(1-16)/(1-2)=75.")], questions=["1. Find term 15 of 4,7,10,...","2. Find sum first 20 terms of 2,6,10,...","3. Find term 8 of 3,6,12,...","4. Find sum first 6 terms of 2,6,18,...","5. Find infinite sum 12+6+3+...","6. In an AP, term 3=11 and term 8=31. Find a and d."], answers=["a=4,d=3: 4+14(3)=46.","n/2[2a+(n-1)d]=10[4+76]=800.","3(2^7)=384.","2(1-3^6)/(1-3)=728.","12/(1-1/2)=24.","a+2d=11, a+7d=31, so d=4 and a=3."], footer="Rohan Study System | P1 Day 10"),
dict(day=11, filename="p1-day-11-differentiation.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 11", title="Differentiation", subtitle="Gradients, tangents and normals", aim="Differentiate powers and use the derivative as a gradient.", intro="The derivative tells you how fast y changes as x changes.", notes=["d/dx(x^n)=n x^(n-1).", "Constants differentiate to 0.", "Differentiate every term separately.", "At x=a, substitute a into dy/dx for the tangent gradient.", "Normal gradient is the negative reciprocal of tangent gradient."], memory="Bring the power down, then reduce it by one.", worked=[("Derivative","y=3x^4-2x^2+7 gives dy/dx=12x^3-4x."),("Tangent","y=x^2+1 at x=2: point (2,5), gradient 4, so y-5=4(x-2).")], questions=["1. Differentiate x^5.","2. Differentiate 4x^3-3x+8.","3. Find gradient of y=x^3-2x at x=2.","4. Find tangent to y=x^2+3 at x=1.","5. Find normal to y=x^2 at x=2.","6. If y=2x^3+kx has gradient 13 at x=1, find k."], answers=["5x^4.","12x^2-3.","dy/dx=3x^2-2; gradient 10.","Point (1,4), m=2: y=2x+2.","Tangent m=4, normal m=-1/4; point (2,4): y-4=-(1/4)(x-2).","dy/dx=6x^2+k; 6+k=13, so k=7."], footer="Rohan Study System | P1 Day 11"),
dict(day=12, filename="p1-day-12-stationary-points.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 12", title="Stationary points", subtitle="Turning points and optimisation", aim="Find, classify and interpret stationary points.", intro="At a stationary point, the tangent is horizontal, so dy/dx=0.", notes=["Solve dy/dx=0 to find stationary x-values.", "Substitute into y to find coordinates.", "Second derivative positive: local minimum; negative: local maximum.", "A sign change + to - is a maximum; - to + is a minimum."], memory="Differentiate, equal zero, solve, substitute, classify.", worked=[("Classify","y=x^2-4x+1. dy/dx=2x-4=0 gives x=2; y=-3. d2y/dx2=2>0, so minimum (2,-3)."),("Cubic","y=x^3-3x: dy/dx=3x^2-3=0 gives x=+-1.")], questions=["1. Find stationary point of y=x^2+6x+2.","2. Classify it.","3. Find stationary x-values of y=x^3-12x.","4. Find and classify both stationary points in Q3.","5. Find minimum value of x^2-8x+20.","6. Rectangle perimeter is 20. If sides are x and 10-x, find maximum area."], answers=["dy/dx=2x+6=0, x=-3; y=-7.","d2y/dx2=2>0, so a minimum.","3x^2-12=0, so x=+-2.","At x=-2, y=16 and second derivative -12: maximum. At x=2, y=-16 and second derivative 12: minimum.","Stationary x=4; minimum value 4.","A=x(10-x)=10x-x^2. A'=10-2x=0 gives x=5; maximum area 25."], footer="Rohan Study System | P1 Day 12"),
dict(day=13, filename="p1-day-13-integration.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 13", title="Integration", subtitle="Antiderivatives, constants and areas", aim="Reverse differentiation and evaluate definite integrals.", intro="Integration rebuilds a function from its rate of change.", notes=["Integral x^n dx=x^(n+1)/(n+1)+C for n not equal to -1.", "Add C for an indefinite integral.", "Use a given point to find C.", "For a definite integral, evaluate upper minus lower.", "Area may require splitting where the curve crosses the axis."], memory="Increase the power by one, divide by the new power.", worked=[("Indefinite","Integral (6x^2-4) dx=2x^3-4x+C."),("Definite","Integral from 0 to 2 of 3x^2 dx=[x^3]0 to 2=8.")], questions=["1. Integrate 4x^3.","2. Integrate 6x^2-2x+5.","3. Given dy/dx=2x+3 and y=5 at x=1, find y.","4. Evaluate integral 0 to 3 of 2x dx.","5. Evaluate integral 1 to 2 of (3x^2+1) dx.","6. Find area under y=4-x^2 from x=0 to x=2."], answers=["x^4+C.","2x^3-x^2+5x+C.","y=x^2+3x+C; 5=1+3+C, so C=1. y=x^2+3x+1.","[x^2]0 to 3=9.","[x^3+x]1 to 2=(10)-(2)=8.","[4x-x^3/3]0 to 2=8-8/3=16/3."], footer="Rohan Study System | P1 Day 13"),
dict(day=14, filename="p1-day-14-consolidation.pdf", kicker="AS MATHEMATICS - PURE 1 - DAY 14", title="P1 consolidation", subtitle="A mixed checkpoint from quadratics to calculus", aim="Retrieve methods without topic labels and diagnose the next weak area.", intro="Mixed practice trains the hardest exam skill: selecting the method yourself.", notes=["Read the command word and write the topic beside each question only after attempting it.", "If stuck, write the relevant formula before doing arithmetic.", "Check algebra, interval, units and exact form.", "Target: at least 5 of 6 fully correct."], memory="Choose method, show structure, calculate, check.", worked=[("Model selection","A tangent question needs differentiation; an arc needs radians; a repeated root needs discriminant zero."),("Repair rule","Do not erase an error. Mark the first wrong line, state the rule, then redo the whole question cleanly.")], questions=["1. Solve x^2-7x+10=0.","2. Find inverse of f(x)=3x-4.","3. Find line through (2,1) perpendicular to y=2x+3.","4. Find coefficient of x^2 in (1+2x)^4.","5. Find stationary point of y=x^2-6x+4.","6. Evaluate integral 0 to 2 of (3x^2+2) dx."], answers=["(x-5)(x-2)=0, so x=2 or 5.","f^-1(x)=(x+4)/3.","Gradient -1/2; y-1=-(1/2)(x-2), so y=-x/2+2.","C(4,2)2^2=24.","dy/dx=2x-6=0 gives x=3; y=-5. Minimum.","[x^3+2x]0 to 2=8+4=12."], footer="Rohan Study System | P1 Day 14")]

M1 = [
dict(day=4, filename="m1-day-04-friction.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 4", title="Friction", subtitle="Normal reaction and limiting equilibrium", aim="Draw friction correctly and use F<=mu R.", intro="Friction acts along a contact surface and opposes actual or impending motion.", notes=["Normal reaction R acts perpendicular to the surface.", "Friction F acts parallel to the surface.", "Always F<=mu R; equality holds only at limiting equilibrium.", "On a horizontal surface with no other vertical forces, R=mg.", "Decide the likely direction of motion before drawing friction."], memory="Friction is not automatically mu R; use F=mu R only when limiting or about to slip.", worked=[("Horizontal pull","Mass 5 kg, mu=0.3, limiting: R=5g, so F=0.3(5g)=1.5g N."),("Equilibrium","If a horizontal pull P is balanced before limiting, F=P and verify P<=mu R.")], questions=["1. A 4 kg block rests horizontally. Find R.","2. If mu=0.25, find limiting friction.","3. A 6 N pull keeps it at rest. Find actual friction.","4. Will a 12 N pull move it? Use g=9.8.","5. A 10 kg block is limiting under a horizontal force P; mu=0.4. Find P.","6. Explain why writing F=mu R for every problem is wrong."], answers=["R=4g=39.2 N.","Fmax=0.25(39.2)=9.8 N.","F=6 N, opposite the pull.","Yes; 12>9.8 N.","R=98 N; P=F=0.4(98)=39.2 N.","Static friction adjusts up to its maximum; equality occurs only at limiting equilibrium."], footer="Rohan Study System | M1 Day 4"),
dict(day=5, filename="m1-day-05-inclined-planes.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 5", title="Inclined planes", subtitle="Resolving weight and friction", aim="Resolve forces parallel and perpendicular to a slope.", intro="Choose axes along and perpendicular to the plane so most forces sit on an axis.", notes=["Weight mg acts vertically downward.", "Component down slope is mg sin theta.", "Component into slope is mg cos theta.", "If no other perpendicular force, R=mg cos theta.", "Friction opposes motion or impending motion along the plane."], memory="Parallel uses sin; perpendicular uses cos when theta is the plane angle.", worked=[("Smooth plane","Mass 3 kg on 30 degrees: acceleration down slope is g sin30=4.9 m/s^2."),("Rough plane","R=mg cos theta; find friction, then apply F=ma along slope.")], questions=["1. Resolve weight of 5 kg parallel to a 30 degree slope.","2. Resolve it perpendicular to the slope.","3. Find R on a smooth 30 degree slope.","4. Find acceleration down the smooth slope.","5. If friction 10 N acts up the slope, find acceleration.","6. For mu=0.2 at limiting equilibrium, write the equation along the slope."], answers=["5g sin30=24.5 N down slope.","5g cos30=42.4 N into slope.","R=42.4 N.","a=g sin30=4.9 m/s^2.","5a=24.5-10, so a=2.9 m/s^2 down slope.","mg sin theta=mu mg cos theta, so tan theta=mu."], footer="Rohan Study System | M1 Day 5"),
dict(day=6, filename="m1-day-06-connected-particles.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 6", title="Connected particles", subtitle="Strings, pulleys and tension", aim="Build one force equation for each particle and solve simultaneously.", intro="Particles joined by a light inextensible string share the same acceleration magnitude.", notes=["Light string means its mass is ignored.", "Smooth pulley means the tension is the same on both sides.", "Choose one direction of motion for the whole system.", "Write F=ma separately for each particle.", "Add equations to eliminate tension; substitute back to find it."], memory="Same a, same T, separate equations.", worked=[("Hanging pair","Masses 3 and 2 kg: 3g-T=3a; T-2g=2a. Add: g=5a, so a=g/5; then T=2g+2a."),("Check","T lies between the two weights for a simple hanging pair.")], questions=["1. Masses 5 kg and 3 kg hang. Write both equations.","2. Find acceleration.","3. Find tension.","4. A 4 kg table block connects to 2 kg hanging, smooth surfaces. Write equations.","5. Find acceleration and tension for Q4.","6. State two assumptions that make tension equal throughout."], answers=["5g-T=5a; T-3g=3a.","2g=8a, so a=g/4=2.45 m/s^2.","T=3g+3a=36.75 N.","For 4 kg: T=4a. For 2 kg: 2g-T=2a.","2g=6a, a=g/3=3.27 m/s^2; T=13.1 N.","The string is light and the pulley is smooth."], footer="Rohan Study System | M1 Day 6"),
dict(day=7, filename="m1-day-07-equilibrium.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 7", title="Equilibrium", subtitle="Resolving forces in two directions", aim="Use zero resultant force to solve particle equilibrium.", intro="A particle in equilibrium has no acceleration, so forces balance in every direction.", notes=["Equilibrium means resultant force is zero.", "Resolve horizontally: sum Fx=0.", "Resolve vertically: sum Fy=0.", "A force P at angle theta has components P cos theta horizontally and P sin theta vertically.", "A string pulls away from the particle along the string."], memory="Draw arrows first; resolve second; solve last.", worked=[("Two components","A 10 N force at 30 degrees above horizontal has horizontal component 10cos30 and vertical component 10sin30."),("Balance","If tension T balances a 12 N horizontal force, the horizontal components must total 12 N in the opposite direction.")], questions=["1. Resolve 20 N at 60 degrees above horizontal.","2. A particle has 8 N right and P left. Find P.","3. Forces 6 N right and 8 N up are balanced by one force. Find its magnitude.","4. State its direction as components.","5. A weight 50 N is supported by two equal strings at 30 degrees above horizontal. Find each tension.","6. Explain why equilibrium does not necessarily mean stationary."], answers=["Horizontal 10 N; vertical 10sqrt(3) N.","P=8 N.","sqrt(6^2+8^2)=10 N.","6 N left and 8 N down.","2T sin30=50, so T=50 N.","It can move with constant velocity because acceleration is zero."], footer="Rohan Study System | M1 Day 7"),
dict(day=8, filename="m1-day-08-work-energy.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 8", title="Work and energy", subtitle="Kinetic energy, potential energy and work", aim="Track energy transfers and use work-energy equations.", intro="Energy is measured in joules; work is energy transferred by a force through a distance.", notes=["Work by constant force along motion: W=Fs.", "Kinetic energy KE=(1/2)mv^2.", "Gravitational potential energy GPE=mgh.", "Work done by the resultant force equals change in KE.", "Against resistance, input work becomes KE, GPE and energy lost."], memory="Write an energy before-and-after line before inserting numbers.", worked=[("Speed change","2 kg from 3 to 7 m/s: change KE=0.5(2)(49-9)=40 J."),("Lift","5 kg raised 2 m gains GPE=5g(2)=10g J.")], questions=["1. Find KE of 4 kg moving at 6 m/s.","2. Find GPE gained by 3 kg raised 5 m.","3. A 20 N force moves 8 m along its direction. Find work.","4. A 2 kg body starts from rest; 36 J resultant work is done. Find speed.","5. A 5 kg body falls 4 m from rest without resistance. Find speed.","6. A 50 N force pulls 3 m while 10 N resistance acts. Find net work."], answers=["0.5(4)(36)=72 J.","3g(5)=147 J.","20(8)=160 J.","36=0.5(2)v^2, so v=6 m/s.","mgh=0.5mv^2, so v=sqrt(2gh)=8.85 m/s.","(50-10)(3)=120 J."], footer="Rohan Study System | M1 Day 8"),
dict(day=9, filename="m1-day-09-power.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 9", title="Power", subtitle="Rate of working and force-speed problems", aim="Connect work, time, force and speed.", intro="Power measures how quickly energy is transferred.", notes=["Power P=W/t.", "For a force acting along motion at speed v, P=Fv.", "1 watt=1 joule per second.", "At constant speed, driving force balances resistance.", "Efficiency=useful output power/input power."], memory="Use P=W/t when time is central; use P=Fv when force and speed are central.", worked=[("Machine","2400 J in 30 s gives P=80 W."),("Vehicle","At 20 m/s with driving force 600 N, P=600(20)=12000 W.")], questions=["1. Find power for 900 J in 15 s.","2. A 500 N force acts at 12 m/s. Find power.","3. A 24 kW engine moves at 8 m/s. Find driving force.","4. At constant speed, resistance is 1500 N at 20 m/s. Find engine power.","5. A motor input is 5 kW and useful output 4 kW. Find efficiency.","6. A 2 kW lift raises 100 kg at constant speed. Find speed."], answers=["60 W.","6000 W=6 kW.","F=P/v=24000/8=3000 N.","P=1500(20)=30000 W=30 kW.","4/5=0.8=80%.","P=mgv, so v=2000/(100g)=2.04 m/s."], footer="Rohan Study System | M1 Day 9"),
dict(day=10, filename="m1-day-10-momentum.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 10", title="Momentum and impulse", subtitle="Force over time and velocity changes", aim="Use signed momentum and connect impulse to force.", intro="Momentum includes direction, so choose a positive direction before calculating.", notes=["Momentum p=mv.", "Impulse=change in momentum=m(v-u).", "For constant force, impulse=Ft.", "Newton's second law can be written F=rate of change of momentum.", "Use negative velocity for motion opposite the chosen positive direction."], memory="Choose positive, write signs, then use final minus initial.", worked=[("Impulse","3 kg changes from +4 to -2 m/s: impulse=3(-2-4)=-18 Ns."),("Average force","If that happens in 0.5 s, F=-18/0.5=-36 N.")], questions=["1. Find momentum of 5 kg at 7 m/s.","2. Find impulse when 2 kg changes from 3 to 9 m/s.","3. Find force if change occurs in 0.4 s.","4. A 0.2 kg ball changes from +10 to -6 m/s. Find impulse.","5. If contact lasts 0.08 s, find average force.","6. Explain the meaning of a negative impulse."], answers=["35 kg m/s.","2(9-3)=12 Ns.","12/0.4=30 N.","0.2(-6-10)=-3.2 Ns.","-3.2/0.08=-40 N.","The impulse acts opposite to the chosen positive direction."], footer="Rohan Study System | M1 Day 10"),
dict(day=11, filename="m1-day-11-collisions.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 11", title="Collisions", subtitle="Conservation of momentum", aim="Model one-dimensional collisions with signed velocities.", intro="During a short collision, external impulse is often negligible, so total momentum is conserved.", notes=["Total momentum before=total momentum after.", "Choose one positive direction and sign every velocity.", "If objects stick together, they share one final velocity.", "Momentum is conserved; kinetic energy need not be.", "Check whether the sign of the answer matches the described direction."], memory="Write one before=after momentum equation with signs visible.", worked=[("Stick together","2 kg at 5 m/s hits 3 kg at rest and sticks: 2(5)=(2+3)v, so v=2 m/s."),("Opposite directions","Right is positive, so a particle moving left has negative velocity.")], questions=["1. 4 kg at 6 m/s hits 2 kg at rest and sticks. Find v.","2. Find KE lost in Q1.","3. 3 kg at +4 m/s collides with 1 kg at -2 m/s; they stick. Find v.","4. 2 kg at 5 m/s hits 3 kg at rest. Afterward 2 kg moves at 1 m/s. Find other velocity.","5. A stationary object explodes into 2 kg at +6 m/s and 3 kg. Find the 3 kg velocity.","6. Why is kinetic energy not automatically conserved?"], answers=["24=6v, so v=4 m/s.","Before 72 J; after 48 J; loss 24 J.","12-2=4v, so v=2.5 m/s.","10=2+3v, so v=8/3 m/s.","0=12+3v, so v=-4 m/s.","Some energy may become heat, sound or deformation."], footer="Rohan Study System | M1 Day 11"),
dict(day=12, filename="m1-day-12-mixed-problems.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 12", title="Mixed Mechanics", subtitle="Selecting the right model", aim="Choose between SUVAT, forces, energy, power and momentum.", intro="The question will not name the method. Identify what is conserved or what stays constant.", notes=["Constant acceleration plus u,v,a,s,t suggests SUVAT.", "For forces and acceleration, draw a diagram and use F=ma.", "Heights and speeds often suggest energy.", "Short impacts suggest impulse or momentum.", "Rates of work suggest power."], memory="List known quantities and the requested quantity before selecting an equation.", worked=[("Selection","Speed after falling through a height: energy is shortest. Speed after a stated time at constant acceleration: SUVAT."),("Verification","After solving, check units, sign and physical size.")], questions=["1. From rest, a=3 m/s^2 for 5 s. Find distance.","2. A 4 kg block has 18 N forward and 6 N resistance. Find acceleration.","3. Find speed after falling 5 m from rest.","4. A 2 kW engine works for 30 s. Find work.","5. A 3 kg particle at 4 m/s receives impulse -18 Ns. Find final velocity.","6. A 5 kg block on a table connects to 5 kg hanging, smooth. Find acceleration."], answers=["s=0.5at^2=37.5 m.","Resultant 12 N; a=12/4=3 m/s^2.","v=sqrt(2gh)=9.90 m/s.","W=Pt=2000(30)=60000 J.","3(v-4)=-18, so v=-2 m/s.","5g=10a, so a=g/2=4.9 m/s^2."], footer="Rohan Study System | M1 Day 12"),
dict(day=13, filename="m1-day-13-consolidation.pdf", kicker="AS MATHEMATICS - MECHANICS 1 - DAY 13", title="M1 consolidation", subtitle="A full mixed checkpoint", aim="Complete a closed-notes checkpoint and expose the next priority topic.", intro="A mechanics solution earns clarity from its diagram, equation, direction and units.", notes=["Draw a force or motion sketch.", "Declare a positive direction.", "Write the model equation symbolically before substituting.", "Use g=9.8 m/s^2 unless told otherwise.", "Target: five fully correct solutions."], memory="Diagram, direction, equation, solve, interpret.", worked=[("Exam habit","If acceleration is negative, say whether the particle is slowing or accelerating in the negative direction."),("Correction habit","Classify errors as diagram, sign, formula, algebra or units.")], questions=["1. A car goes from 5 to 17 m/s in 4 s uniformly. Find a and s.","2. A 6 kg block has 30 N forward and 12 N resistance. Find a.","3. Find limiting friction for 8 kg on horizontal ground, mu=0.25.","4. A 2 kg body rises 3 m. Find GPE gained.","5. A 10 kW engine at 5 m/s balances resistance. Find resistance.","6. 2 kg at 8 m/s sticks to 6 kg at rest. Find final speed."], answers=["a=3 m/s^2; s=(5+17)4/2=44 m.","Resultant 18 N; a=3 m/s^2.","R=8g; F=0.25(8g)=19.6 N.","mgh=2g(3)=58.8 J.","F=P/v=10000/5=2000 N.","16=8v, so v=2 m/s."], footer="Rohan Study System | M1 Day 13")]

BUSINESS = [
dict(day=4, filename="business-day-04-market-research.pdf", kicker="AS BUSINESS - DAY 4", title="Market research", subtitle="Customers, data and sampling", aim="Understand how a business learns what customers want.", intro="Marketing starts with identifying and satisfying customer needs profitably.", notes=["Primary research is new data collected for the business.", "Secondary research already exists, such as reports or government data.", "Qualitative data explains opinions; quantitative data uses numbers.", "A sample is a smaller group used to represent a population.", "Reliable research reduces uncertainty but never removes risk."], case="FreshSip plans a low-sugar drink for students. It surveys 20 friends of the founder and finds 90% would buy it. A national report says low-sugar drink sales grew 12% last year.", worked="The survey is primary and quantitative, but the friends may be biased and unrepresentative. Therefore the 90% result could overestimate demand and cause excess inventory.", questions=["1. Define primary research.","2. Define secondary research.","3. Identify one primary and one secondary source in the case.","4. Explain one weakness of FreshSip's sample.","5. Explain one benefit of the national report.","6. Recommend one better research method and justify it."], answers=["New data collected first-hand for a specific purpose.","Existing data originally collected by someone else.","Primary: survey of friends. Secondary: national report.","Friends may share similar preferences; the 90% may not represent all students, causing poor demand forecasts.","It shows a wider market trend cheaply and quickly, helping FreshSip judge whether demand is growing.","Use a larger stratified sample from several schools/colleges so ages and locations are represented, improving reliability before launch."], footer="Rohan Study System | Business Day 4"),
dict(day=5, filename="business-day-05-product-price.pdf", kicker="AS BUSINESS - DAY 5", title="Product and price", subtitle="The first half of the marketing mix", aim="Connect product and pricing decisions to objectives and customers.", intro="The marketing mix is a coordinated set of product, price, promotion and place decisions.", notes=["Product includes design, quality, features, branding and packaging.", "A USP is a feature customers see as meaningfully different.", "Cost-plus pricing adds a markup to unit cost.", "Penetration pricing starts low to gain market share.", "Price skimming starts high for a distinctive new product."], case="Nova Tutors launches an exam app with live feedback. Unit service cost is PKR 600 per student monthly. It considers PKR 900 cost-plus pricing or PKR 500 penetration pricing for the first three months.", worked="PKR 500 penetration pricing may attract price-sensitive students quickly, increasing trial and market share. However, it is below the PKR 600 unit cost, so every user initially contributes a loss.", questions=["1. Define USP.","2. Calculate markup percentage at a PKR 900 price on PKR 600 cost.","3. Identify the penetration price.","4. Explain one benefit of penetration pricing to Nova.","5. Explain one risk of that price.","6. Recommend a launch price with one condition."], answers=["A product feature or benefit perceived as different from competitors.","Markup=300/600 x 100=50%.","PKR 500.","A low price may encourage rapid trial and market share, useful for a new app needing users and reviews.","It is below unit cost, so rapid growth could increase losses and make a later price rise difficult.","PKR 900 is safer if live feedback is valued and demand is less price-sensitive; otherwise use a time-limited discount above cost."], footer="Rohan Study System | Business Day 5"),
dict(day=6, filename="business-day-06-promotion-place.pdf", kicker="AS BUSINESS - DAY 6", title="Promotion and place", subtitle="Reaching and persuading the target market", aim="Select promotion and distribution methods for a case.", intro="Promotion communicates; place makes the product available where and when customers want it.", notes=["Above-the-line promotion reaches mass audiences through paid media.", "Below-the-line methods target customers more directly, such as email or sales promotion.", "Digital promotion can be targeted and measured.", "Direct distribution sells without an intermediary.", "A channel with intermediaries can expand reach but reduces control and margin."], case="GlowSkin is a small online skincare brand aimed at women aged 18-25. It has PKR 300,000 for launch promotion and no physical shops. Influencers offer measurable discount codes; a national billboard costs the full budget.", worked="Micro-influencers fit the 18-25 target and codes reveal conversions. Therefore GlowSkin can adjust spending and protect its limited budget better than with one billboard.", questions=["1. Define promotion.","2. Define direct distribution.","3. Identify one targeted method in the case.","4. Explain one benefit of discount codes.","5. Explain one drawback of online-only place.","6. Recommend a promotional method."], answers=["Communication used to inform or persuade customers.","Selling from producer directly to customer without an intermediary.","Influencer promotion using trackable codes.","Codes measure which creator generates sales, so scarce budget can move toward effective channels.","Customers cannot test products physically, possibly reducing trust and conversion.","Use several relevant micro-influencers, conditional on audience authenticity and cost per conversion; avoid risking the full budget on one billboard."], footer="Rohan Study System | Business Day 6"),
dict(day=7, filename="business-day-07-production-productivity.pdf", kicker="AS BUSINESS - DAY 7", title="Production and productivity", subtitle="Job, batch, flow and efficiency", aim="Choose a production method and calculate productivity.", intro="Operations transforms inputs into outputs customers value.", notes=["Job production makes one customised item at a time.", "Batch production makes groups of identical items.", "Flow production makes standardised output continuously.", "Labour productivity=output/number of workers.", "Higher productivity can lower unit cost, but quality and motivation still matter."], case="CraftDesk employs 12 workers and makes 240 standard desks a week in batches. A machine would raise output to 360 with the same workforce but requires training and may reduce custom options.", worked="Current productivity=240/12=20 desks per worker. With the machine it becomes 30, a 50% increase, which may reduce labour cost per desk.", questions=["1. Define batch production.","2. Calculate current labour productivity.","3. Calculate new productivity.","4. Calculate percentage increase.","5. Explain one benefit of the machine.","6. Explain one risk of moving toward more standardised production."], answers=["Producing a group of identical items before switching to another group.","240/12=20 desks per worker per week.","360/12=30.","(30-20)/20 x 100=50%.","Higher output with the same workforce may lower unit labour cost and meet more orders.","Less customisation may weaken CraftDesk's differentiation and lose customers who value bespoke designs."], footer="Rohan Study System | Business Day 7"),
dict(day=8, filename="business-day-08-capacity-quality.pdf", kicker="AS BUSINESS - DAY 8", title="Capacity and quality", subtitle="Utilisation, inventory and quality control", aim="Calculate capacity use and analyse operational trade-offs.", intro="Capacity is the maximum output possible in a period.", notes=["Capacity utilisation=(actual output/maximum output)x100.", "High utilisation spreads fixed cost but leaves little room for surges or maintenance.", "Inventory protects against shortages but ties up cash and may become obsolete.", "Quality control inspects output; quality assurance builds quality into the process.", "Poor quality creates waste, returns and reputational damage."], case="BakeBox can make 10,000 snack boxes monthly and currently makes 9,200. Defect rate is 6%. A supermarket order needs another 1,200 boxes next month.", worked="Capacity utilisation=9200/10000 x 100=92%. The extra order exceeds spare capacity of 800, so BakeBox needs overtime, outsourcing or extra capacity.", questions=["1. Define capacity utilisation.","2. Calculate BakeBox's utilisation.","3. Calculate spare capacity.","4. Explain one risk of accepting the order immediately.","5. Explain one benefit of quality assurance.","6. Recommend one operational response."], answers=["Actual output as a percentage of maximum possible output.","92%.","10,000-9,200=800 boxes.","Required extra output is 1,200, above spare capacity; rushed overtime may worsen the 6% defect rate and harm the supermarket relationship.","Preventing errors during production can reduce waste and returns, lowering cost and protecting reputation.","Use limited vetted outsourcing or temporary capacity only if quality standards can be monitored; otherwise negotiate a phased delivery."], footer="Rohan Study System | Business Day 8"),
dict(day=9, filename="business-day-09-motivation.pdf", kicker="AS BUSINESS - DAY 9", title="Motivation", subtitle="Why people work well", aim="Apply financial and non-financial motivation methods.", intro="Motivation is the willingness of employees to work effectively toward objectives.", notes=["Pay matters, but motivation also depends on recognition, responsibility and development.", "Piece rate links pay to output but may damage quality.", "Job rotation changes tasks; job enrichment adds responsibility and challenge.", "Training can improve skill, confidence and retention.", "The best method depends on worker needs and the nature of the job."], case="CallPro has 40 agents. Labour turnover is 30% and complaints are rising. Managers propose a bonus based only on number of calls, while agents ask for coaching and more authority to solve customer problems.", worked="A volume-only bonus may increase calls, but agents could rush customers. Complaints may rise further, damaging retention and reputation.", questions=["1. Define labour turnover.","2. Identify one financial motivator.","3. Identify two non-financial motivators in the case.","4. Explain one risk of the proposed bonus.","5. Explain one benefit of job enrichment.","6. Recommend a motivation package."], answers=["The proportion of employees leaving an organisation over a period.","Bonus based on number of calls.","Coaching/training and greater authority/responsibility.","Agents may shorten calls to earn bonuses, reducing service quality and increasing complaints.","More authority can create achievement and faster problem resolution, improving satisfaction for staff and customers.","Combine coaching and controlled decision authority with a balanced bonus using quality and customer satisfaction, not call volume alone."], footer="Rohan Study System | Business Day 9"),
dict(day=10, filename="business-day-10-leadership.pdf", kicker="AS BUSINESS - DAY 10", title="Leadership and organisation", subtitle="Styles, delegation and communication", aim="Match leadership style and structure to a situation.", intro="Leadership influences people; management plans and coordinates resources.", notes=["Autocratic leaders make decisions centrally.", "Democratic leaders consult employees.", "Laissez-faire gives substantial freedom to skilled workers.", "Delegation passes authority but the manager keeps accountability.", "A wide span of control means one manager supervises many people."], case="MedCode has 18 expert developers. A security incident needs a fix within four hours. For its next six-month product, developers say consultation will improve innovation and commitment.", worked="Autocratic leadership may suit the urgent incident because one fast decision reduces delay. It may be less suitable for the six-month product, where expert ideas improve innovation.", questions=["1. Define delegation.","2. Define democratic leadership.","3. Explain why autocratic leadership fits the incident.","4. Explain one drawback of using it for six months.","5. Explain one benefit of delegation to expert developers.","6. Recommend leadership styles for both situations."], answers=["Passing authority to a subordinate to perform a task while the manager remains accountable.","A style in which employees are consulted before decisions.","The four-hour deadline needs speed and clear authority, reducing time spent consulting.","Experts may feel ignored, lowering motivation and reducing useful ideas for innovation.","It uses specialist knowledge and can speed decisions while developing employee responsibility.","Use autocratic direction during the incident, then democratic leadership and delegation for product development, with clear security limits."], footer="Rohan Study System | Business Day 10"),
dict(day=11, filename="business-day-11-break-even.pdf", kicker="AS BUSINESS - DAY 11", title="Costs and break-even", subtitle="Contribution, break-even and decisions", aim="Calculate break-even and interpret what the figures mean.", intro="Break-even is the output where total revenue equals total cost.", notes=["Total cost=fixed cost+total variable cost.", "Contribution per unit=price-variable cost per unit.", "Break-even output=fixed cost/contribution per unit.", "Margin of safety=actual output-break-even output.", "Break-even assumes values such as price and variable cost stay constant."], case="BeanCart sells cups for PKR 500. Variable cost is PKR 200 per cup and monthly fixed cost is PKR 900,000. It expects to sell 3,500 cups.", worked="Contribution=500-200=PKR 300. Break-even=900,000/300=3,000 cups. Margin of safety=500 cups.", questions=["1. Define fixed cost.","2. Calculate contribution per cup.","3. Calculate break-even output.","4. Calculate margin of safety.","5. Calculate profit at 3,500 cups.","6. Explain one limitation of the break-even result."], answers=["A cost that does not change directly with output in the period.","PKR 300.","3,000 cups.","3,500-3,000=500 cups.","Total contribution 3,500(300)=1,050,000; profit=150,000.","Demand, price or variable cost may change; if sales are below forecast or costs rise, actual break-even will differ."], footer="Rohan Study System | Business Day 11"),
dict(day=12, filename="business-day-12-cash-flow.pdf", kicker="AS BUSINESS - DAY 12", title="Cash flow", subtitle="Forecasts, shortages and working capital", aim="Calculate closing balances and recommend responses to shortages.", intro="Profit is not cash. A profitable business can fail if it cannot pay bills when due.", notes=["Net cash flow=cash inflows-cash outflows.", "Closing balance=opening balance+net cash flow.", "One month's closing balance becomes the next month's opening balance.", "A forecast identifies timing problems, not guaranteed outcomes.", "Responses include changing payment timing, overdraft, reducing inventory or delaying spending."], case="PixelPrint opens September with PKR 400,000. Expected inflows are PKR 700,000 and outflows PKR 1,250,000 because a printer is bought. October inflows are PKR 1,100,000 and outflows PKR 650,000.", worked="September net flow=700,000-1,250,000=-550,000. Closing=-150,000, so PixelPrint must arrange finance or change timing before September.", questions=["1. Define cash inflow.","2. Calculate September net cash flow.","3. Calculate September closing balance.","4. Calculate October closing balance.","5. Explain why profit may still be positive in September.","6. Recommend one response to the September shortage."], answers=["Money entering the business during a period.","-PKR 550,000.","400,000-550,000=-PKR 150,000.","Opening -150,000 plus net flow 450,000 gives PKR 300,000.","The printer is a cash payment for a long-term asset; accounting profit and cash timing are different.","Arrange an overdraft of at least PKR 150,000 plus a buffer, or negotiate staged printer payments, because October recovers cash; compare interest and supplier terms."], footer="Rohan Study System | Business Day 12"),
dict(day=13, filename="business-day-13-consolidation.pdf", kicker="AS BUSINESS - DAY 13", title="Business consolidation", subtitle="A mixed case and longer judgement", aim="Combine marketing, operations, people and finance in one decision.", intro="Strong Business answers select relevant ideas, apply exact facts and develop consequences.", notes=["Knowledge names and explains the business idea.", "Application uses an exact case fact.", "Analysis builds a because-therefore chain.", "Evaluation judges using objectives, time, risk and conditions.", "A conclusion must answer the question, not merely repeat both sides."], case="StudyHub has 2,000 paying students at PKR 1,200 monthly. Capacity is 2,200. Complaints rose after staff turnover reached 25%. A school offers 1,000 new users at PKR 800 each. New servers cost PKR 500,000 and training costs PKR 200,000. StudyHub has PKR 300,000 cash and can borrow the rest at 16%.", worked="The school contract adds PKR 800,000 monthly revenue, but users would exceed current capacity by 800. Without servers and training, service quality and complaints may worsen, risking existing customers.", questions=["1. Calculate current monthly revenue.","2. Calculate contract monthly revenue.","3. Identify two operational problems.","4. Explain one benefit of accepting the contract.","5. Explain one risk of loan finance.","6. Recommend whether StudyHub should accept, with conditions."], answers=["2,000 x 1,200=PKR 2,400,000.","1,000 x 800=PKR 800,000.","Capacity would be exceeded; complaints and 25% turnover suggest service and staffing weakness.","Revenue and scale increase, and a school contract may strengthen reputation, provided capacity supports users.","At 16%, interest and repayments reduce cash flow; StudyHub already has only PKR 300,000 against PKR 700,000 investment.","Accept only if the school commits long enough to recover investment and StudyHub installs servers and trains/retains staff before launch; otherwise quality risk may damage 2,000 higher-paying users."], footer="Rohan Study System | Business Day 13")]


if __name__ == "__main__":
    paths = [math_pack(s) for s in P1] + [math_pack(s) for s in M1] + [business_pack(s) for s in BUSINESS]
    if len(paths) != 30:
        raise RuntimeError(f"Expected 30 PDFs, created {len(paths)}")
    print("\n".join(str(p) for p in paths))
